### ISSUE TITLE
Project Kanban Setup 

### ISSUE THREAD

**Issue by Benmuiruri** [Benmuiruri/stream-it-movie-library#21]
Link to collaborative GitHub project https://github.com/Benmuiruri/stream-it-capstone

The project has two collaborators: [Ben Muiruri](https://github.com/Benmuiruri) and [Olawade Bamidele](https://github.com/olawalecoder)

**Comment by Whoistolu** [comment]
Hi Team,
@Benmuiruri and @olawalecoder 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] [REQUIRED] Kindly ensure you have 4 columns in total. Currently, the `In review` column is missing. The `In review` column should be just after the `In progress` column. This column shows the cards that are currently undergoing reviews by the other partner, kindly go ahead to implement this.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Benmuiruri** [comment]
Thanks for the review @Whoistolu I have made the change

**Comment by prolajumokeoni** [comment]
Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
